// Generated by gencpp from file control_tb3/2Velocity.msg
// DO NOT EDIT!


#ifndef CONTROL_TB3_MESSAGE_2VELOCITY_H
#define CONTROL_TB3_MESSAGE_2VELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_tb3
{
template <class ContainerAllocator>
struct 2Velocity_
{
  typedef 2Velocity_<ContainerAllocator> Type;

  2Velocity_()
    : right(0.0)
    , left(0.0)  {
    }
  2Velocity_(const ContainerAllocator& _alloc)
    : right(0.0)
    , left(0.0)  {
  (void)_alloc;
    }



   typedef double _right_type;
  _right_type right;

   typedef double _left_type;
  _left_type left;





  typedef boost::shared_ptr< ::control_tb3::2Velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_tb3::2Velocity_<ContainerAllocator> const> ConstPtr;

}; // struct 2Velocity_

typedef ::control_tb3::2Velocity_<std::allocator<void> > 2Velocity;

typedef boost::shared_ptr< ::control_tb3::2Velocity > 2VelocityPtr;
typedef boost::shared_ptr< ::control_tb3::2Velocity const> 2VelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_tb3::2Velocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_tb3::2Velocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_tb3

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'control_tb3': ['/home/turltebot3-raspi/catkin_ws/src/control_tb3/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_tb3::2Velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_tb3::2Velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_tb3::2Velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_tb3::2Velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_tb3::2Velocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_tb3::2Velocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_tb3::2Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69961745475ae50d2f0b8ca4d0df065b";
  }

  static const char* value(const ::control_tb3::2Velocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69961745475ae50dULL;
  static const uint64_t static_value2 = 0x2f0b8ca4d0df065bULL;
};

template<class ContainerAllocator>
struct DataType< ::control_tb3::2Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_tb3/2Velocity";
  }

  static const char* value(const ::control_tb3::2Velocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_tb3::2Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 right\n\
float64 left\n\
";
  }

  static const char* value(const ::control_tb3::2Velocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_tb3::2Velocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.right);
      stream.next(m.left);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct 2Velocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_tb3::2Velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_tb3::2Velocity_<ContainerAllocator>& v)
  {
    s << indent << "right: ";
    Printer<double>::stream(s, indent + "  ", v.right);
    s << indent << "left: ";
    Printer<double>::stream(s, indent + "  ", v.left);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_TB3_MESSAGE_2VELOCITY_H
